spring:
  security:
    oauth2:
      client:
        provider:
          dzhw:
            issuer-uri: ${DZHW_ISSUER_URI}
        registration:
          dzhw:
            client-id: ${DZHW_CLIENT_ID}
            client-secret: ${DZHW_CLIENT_SECRET}
mdm:
  endpoint: ${vcap.services.mdm.credentials.endpoint}
