name: Build
on:
  push:
    branches-ignore:
      - development
      - test
      - master
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 15
      uses: actions/setup-java@v4.1.0
      with:
        distribution: 'adopt'
        java-version: '15'
    - name: Cache maven artifacts
      uses: actions/cache@v4
      env:
        cache-name: cache-maven-artifacts
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.m2
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
    - name: Extract branch name
      shell: bash
      run: echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
    - name: Build with Maven
      run: ./deploy/build.sh unused ${{ env.BRANCH }}
      env:
        MDM_ENDPOINT: ${{ secrets.MDM_ENDPOINT }}
        FDZ_ISSUER_URI: ${{ secrets.FDZ_ISSUER_URI }}
        FDZ_CLIENT_ID: ${{ secrets.FDZ_CLIENT_ID }}
        FDZ_CLIENT_SECRET: ${{ secrets.FDZ_CLIENT_SECRET }}
    - name: Report build status via Slack
      uses: act10ns/slack@v2
      if: always()
      with:
        status: ${{ job.status }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
