name: Build
on:
  push:
    branches-ignore:
      - development
      - test
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Cache maven artifacts
      uses: actions/cache@v2
      env:
        cache-name: cache-maven-artifacts
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.m2
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
    - name: Get branch name
      uses: nelonoel/branch-name@v1.0.1
    - name: Build with Maven
      run: ./deploy/build.sh unused ${BRANCH_NAME}
      env:
        MDM_ENDPOINT: ${{ secrets.MDM_ENDPOINT }}
        MDM_TASK_PASSWORD: ${{ secrets.MDM_TASK_PASSWORD }}
        MDM_TASK_USER: ${{ secrets.MDM_TASK_USER }}
    - name: Report build status via Slack
      uses: act10ns/slack@v1
      if: always()
      with:
        status: ${{ job.status }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
